language: node_js

node_js:
  - "8"

cache:
  directories:
  - node_modules

before_install:
  - echo $GitHubPrivateKey > private_key.rsa
  - ssh -i private_key.rsa -T git@github.com
  - ssh -vT git@github.com


install:
  - npm i

script:
  - npm run safe-sync