language: node_js

node_js:
  - "8"

cache:
  directories:
  - node_modules

before_install:
  - echo $GitHubPrivateKey > private_key.rsa
  - ssh-add private_key.rsa

install:
  - npm i

script:
  - npm run safe-sync