language: node_js

node_js:
  - "8"

cache:
  directories:
  - node_modules

before_install:
  - echo $GitHubPrivateKey > private_key.rsa
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/private_key.rsa\n" >> ~/.ssh/config


install:
  - npm i

script:
  - npm run safe-sync